### ISSUE TITLE
async.each breaks

### ISSUE THREAD

**Issue by rphillips** [scottnonnenberg/notate#1]
The blog post mentions the following snippet runs in parallel, but it runs in series:

```
function fiveSteps(cb) {
  async.series([
    step1,
    step2,
    step3,
    step4,
    step5,
  ], ...
};
```

If I change `async.series` to `async.each` to run each step in parallel, then the following gets dumped out:

```
message:
undefined

stack:
**notate: afterFiveSteps (/Users/ryan.phillips/tmp/blog-code/notate/3_five_steps_with_metadata.js:82:9)

prettyPrint:
{ [Function: step1] param: 'param' }
message:
undefined
```

Looks like a cool library, but I think the `.each` variation should throw a useful stack.

**Comment by scottnonnenberg** [comment]
The second param in `each` is the function to be applied to each item in the first array parameter. So it looks like your output is what you get if you pass a non-error into `notate`! I could probably make that a little bit better - the stack should be included in the `prettyPrint()`...

Note that the scenario you describe did work for me when I changed it to `async.parallel`...

Maybe you could post your entire file?

**Comment by scottnonnenberg** [comment]
I can get the single notate-provided stack entry (from your 'stack:' output above) to show up in the `prettyPrint()` if I change the check here: https://github.com/scottnonnenberg/notate/blob/7af0f5adcea65f48b1ef4be22151dae94d0104e2/src/notate.js#L115

I was thinking of continuing if:
1. it's an `Error`, or
2. it has a `stack` property

What do you think?

**Comment by rphillips** [comment]
Ah hah! I am actually wanting `async.parallel` which works fine. async.each has the wrong prototype for what I was using it for.
